In [23]:
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
### Sentence
sent = [
    "the glss of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "Your videos are good"
]

In [25]:
sent

['the glss of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'Your videos are good']

In [26]:
## Define the vocabulary size
voc_size = 10000

In [27]:
sent

['the glss of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'Your videos are good']

In [28]:
### One hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2357, 8801, 5685, 9189],
 [2357, 78, 5685, 1887],
 [2357, 1014, 5685, 3221],
 [9108, 1123, 3321, 4020, 8781],
 [9108, 1123, 3321, 4020, 7669],
 [9696, 2357, 8521, 5685, 1949],
 [1885, 6418, 1644, 4020]]

In [29]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2357 8801 5685 9189]
 [   0    0    0    0 2357   78 5685 1887]
 [   0    0    0    0 2357 1014 5685 3221]
 [   0    0    0 9108 1123 3321 4020 8781]
 [   0    0    0 9108 1123 3321 4020 7669]
 [   0    0    0 9696 2357 8521 5685 1949]
 [   0    0    0    0 1885 6418 1644 4020]]


In [31]:
dim = 10

In [32]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [33]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[[-1.9192839e-02, -3.3069752e-02, -9.6170418e-03, -3.8978755e-02,
         -4.8133995e-02,  4.5127496e-03,  1.2467280e-03,  1.3101760e-02,
          3.1695019e-02,  3.9827276e-02],
        [-1.9192839e-02, -3.3069752e-02, -9.6170418e-03, -3.8978755e-02,
         -4.8133995e-02,  4.5127496e-03,  1.2467280e-03,  1.3101760e-02,
          3.1695019e-02,  3.9827276e-02],
        [-1.9192839e-02, -3.3069752e-02, -9.6170418e-03, -3.8978755e-02,
         -4.8133995e-02,  4.5127496e-03,  1.2467280e-03,  1.3101760e-02,
          3.1695019e-02,  3.9827276e-02],
        [-1.9192839e-02, -3.3069752e-02, -9.6170418e-03, -3.8978755e-02,
         -4.8133995e-02,  4.5127496e-03,  1.2467280e-03,  1.3101760e-02,
          3.1695019e-02,  3.9827276e-02],
        [-4.3229986e-02, -6.8626031e-03, -1.3875864e-02, -8.8153966e-03,
          2.0758022e-02, -3.8518716e-02, -1.1236727e-02, -1.7719865e-03,
          4.0246237e-02, -3.0759370e-02],
        [ 1.0973133e-02, -4.7189545e-02, -2.9596865e-02,  3.

In [35]:
embedded_docs[0]

array([   0,    0,    0,    0, 2357, 8801, 5685, 9189])

In [36]:
embedded_docs[1]

array([   0,    0,    0,    0, 2357,   78, 5685, 1887])

In [37]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [ ]:
model.predict(embedded_docs[1])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None